### PR TITLE
fix: removed args input to jx gitops helmfile template as this is redundant now in helmfile template. Replaced with a values file input that accepts multiple files on the command line

### PR DESCRIPTION
**Pull request by chrismellard**

### CODE REVIEW

**Comment by rawlingsj** [comment]
There's a valid test failure which I was gonna fix and push to get this merged but first I used it while debugging the BDD pipelines with this PR https://github.com/jenkins-x/jxr-versions/pull/1822/files.  I kubectl exec'd a locally built version of this PR and ran it in the BDD pipeline but we're not getting yaml templated to the ./config_root dir.  I've had a tinker with the `--output-dir-template` options, managed to get the yaml generating using 
```
--output-dir-template "$OUTPUT_DIR//{{ .Release.Namespace }}"
```
But each nested helmfile overwrites the config_root folder so we only get the last helmfile.yaml templated yaml.  

I might have a bit more time to look later but I think its probably worth trying out fixes locally or by uploading into the BDD pipeline.

**Comment by jstrachan** [comment]
fwiw the output used to be a bit wonky so we used to use various commands like split, move, rename to process the template output & move resources into the right directory tree (cluster, crds, namespaces). 

We could maybe put the output in a folder per namespace then when all the helmfile templates are run, invoke the split / move / rename steps?

**Comment by rawlingsj** [comment]
I've got something working locally using vanilla helmfile template and `--output-dir-tem
plate $(pwd)/$OUTPUT_DIR/{{.Release.Namespace}}` but just tested with jx-gitops thats still not generating them so just looking at that now.  fwiw I kinda prefer using vanilla helmfile template as its clearer whats going on but will try and get this working and worry about that another day.

**Comment by jstrachan** [comment]
yeah - I like the idea of doing as little as we can in `jx gitops helmfile template` (ideally removing it completely some day).

Any other steps we need can be done later on in the makefile.

We need to run split to ensure 1 resource per file which makes life easier for other steps; I do like the rename to enforce canonical file names but it’s not essential. We definitely need to move into the 3 directory trees (cluster, crds & namespaces) to fix ordering issues etc - but those are all existing commands we can put in the makefile

**Comment by rawlingsj** [comment]
yeah - let's avoid the helmfile template, run that in the makefile and this command just does the restructure for the follow steps.  I'm running out of time but maybe able to try that using a custom boot image with our BDD and see what happens.

**Comment by chrismellard** [comment]
pushed a fix for the unit tests. this revealed the fact that values are resolved relative to the helmfile location which isn't going to work for us so I've made all values file locations relative to the `--dir` are

**Comment by rawlingsj** [comment]
FWIW there's a WIP PR here which avoids the jx gitops helmfile template command all together. Along with version stream makefile changes here https://github.com/jenkins-x/jxr-versions/pull/1823

**Pull request merged**
