### PR TITLE
chore: add custom upgrade for external secrets chart

### PR DESCRIPTION
**Pull request by rawlingsj**
this is while we wait for PR https://github.com/external-secrets/kubernetes-external-secrets/pull/615 to merge

### CODE REVIEW

**Comment by chrismellard** [comment]
upstream external secrets PR updated after review so hopefully not too far away from being merged

**Comment by jstrachan** [comment]
replacing with https://github.com/jenkins-x/jx-gitops/pull/597 which should fix the failing tests

**Pull request closed without merging**
